### ISSUE TITLE
Select a license and add texts and logos related to the subsidy

### ISSUE THREAD

**Issue by 0x1026** [Projecte-UrbanTree/legacy#14]
Our project is publicly available, which means selecting an appropriate license is critical. The license ensures we comply with legal requirements, set expectations for usage, and communicate how others can contribute or redistribute our work. Additionally, we should incorporate logos and information related to the subsidy in our project documentation, as it demonstrates transparency and acknowledges the support received.

This issue aims to:
1. Select and integrate a suitable open-source license, ensuring it aligns with the licenses of our dependencies.
2. Update the project’s documentation with subsidy-related logos and text, improving clarity and visibility.

## Tasks
- [ ] **Document Dependencies and Their Licenses**
Review and document the [dependencies](https://github.com/Projecte-UrbanTree/UrbanTree/network/dependencies) used in the project and their corresponding licenses. This will guide the selection of a compatible and appropriate license for our repository.
- [x] **Choose and Add a License**
Based on the dependency review, choose a license that ensures compliance and suits the project's goals. Update the repository to include the selected license.
- [ ] **Incorporate Subsidy Logos and Texts**
  - [ ] Add the relevant subsidy logos and acknowledgments to the [README.md](https://github.com/Projecte-UrbanTree/UrbanTree/blob/main/README.md)
  - [ ] Ensure the logos meet any required guidelines (e.g., size, positioning, attribution text).
  - [ ] Mention the subsidy support in a dedicated section or prominently in the README for visibility.

## Resources
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
- https://choosealicense.com/
- https://chatgpt.com/share/673ee4f9-24a8-800a-a0ac-c9546a1c8e24

**Comment by 0x1026** [comment]
Hola @joaniglesias-iesmontsia, acabo de descobrir aquesta [web que ens ajuda a escollir una llicència](https://choosealicense.com/), la qual conté una [pàgina que ens interessa](https://choosealicense.com/no-permission/), atès que comenta que si el repositori/projecte/aplicatiu no conté cap llicència, per defecte, prohibeix l'ús, modificació, o la distribució del treball.

**Comment by joaniglesias-iesmontsia** [comment]
Ok. Com que, segons currículum d'M9, la qüestió de les llicències "cau" a l'sprint3, ho deixem pendent fins llavors, doncs formarà part del treball que heu de lliurar en aquell sprint.

**Comment by joaniglesias-iesmontsia** [comment]
Ídem pel que fa a logos i altres imatges (a l'sprint 3 d'M9 toquen, segons currículum, qüestions de contingut multimèdia)

**Comment by 0x1026** [comment]
He demanat ajuda a ChatGPT perquè ens recomani quina llicència hauríem d'utilitzar i aquesta ha estat la seva 
[resposta](https://chatgpt.com/share/673ee4f9-24a8-800a-a0ac-c9546a1c8e24).

**Comment by joaniglesias-iesmontsia** [comment]
Ja ho parlarem a classe.

Salutacions,

*Joan Iglesias Marca*
Professor i tutor de pràctiques
Dep. Informàtica i Comunicacions

*Institut Montsià*



Missatge de Hugoo ***@***.***> del dia dj., 21 de nov. 2024 a
les 8:47:

**Comment by 0x1026** [comment]
D'acord amb la llista de dependències i les seves llicències, totes utilitzen **BSD-3-Clause** o **MIT**, que són llicències permissives i compatibles entre elles. Això us dona molta flexibilitat per triar la llicència del vostre projecte. Aquí teniu algunes recomanacions específiques:

---

### Opcions de llicència per al vostre projecte

1. **MIT**:
   - És una de les llicències més senzilles i permissives.
   - Compatible amb les llicències BSD-3-Clause i MIT de les vostres dependències.
   - Ideal si voleu que altres desenvolupadors puguin utilitzar, modificar i redistribuir el vostre codi amb mínimes restriccions.

   **Text de llicència**: [MIT License](https://opensource.org/licenses/MIT)

2. **BSD-3-Clause**:
   - Aquesta llicència és gairebé tan permissiva com MIT, però amb un requisit addicional: prohibeix utilitzar el nom dels contribuïdors per promocionar versions derivades sense permís explícit.
   - Compatible amb les llicències de les vostres dependències, ja que algunes ja utilitzen aquesta mateixa llicència.

   **Text de llicència**: [BSD 3-Clause License](https://opensource.org/licenses/BSD-3-Clause)

3. **Apache 2.0**:
   - Ofereix permissivitat similar a MIT/BSD-3-Clause, però afegeix protecció davant possibles litigis per patents.
   - Compatible amb les llicències BSD-3-Clause i MIT.
   - Recomanada si creieu que el vostre projecte pot beneficiar-se d'una protecció addicional relacionada amb patents.

   **Text de llicència**: [Apache License 2.0](https://opensource.org/licenses/Apache-2.0)

---

### Recomanació

Atès que totes les vostres dependències tenen llicències permissives (BSD-3-Clause o MIT), podeu optar per qualsevol de les tres opcions anteriors. 

- Si voleu **simplicitat** i ús ampli del codi, trieu **MIT**.
- Si voleu reflectir la llicència de la majoria de les dependències, trieu **BSD-3-Clause**.
- Si busqueu una **protecció addicional contra patents**, trieu **Apache 2.0**.

---

### Implementació

1. **Incloeu el fitxer de llicència**:
   - Creeu un fitxer `LICENSE` al vostre repositori amb el text complet de la llicència seleccionada.

2. **Incloeu crèdits per a les dependències**:
   - Per complir amb les llicències de les vostres dependències, creeu un fitxer `NOTICE` o una secció a la documentació que indiqui que utilitzeu aquestes dependències i esmenti les seves llicències.

3. **Exemple de capçalera per al codi**:
   Afegiu una capçalera als vostres fitxers font amb una línia com aquesta:
   ```php
   // Aquest codi està llicenciat sota la llicència MIT (vegeu el fitxer LICENSE).
   // Inclou dependències de tercers sota llicències compatibles (BSD-3-Clause, MIT).
   ```

Aquesta documentació deixarà clar als usuaris com està regulat l'ús del vostre projecte i les seves dependències. Si necessiteu ajuda redactant algun d'aquests fitxers, digueu-m'ho! 😊

**Comment by joaniglesias-iesmontsia** [comment]
Hola,

Donat que hi ha finançament públic de la UE, proposo la llicència [EUPL 1.2](https://eupl.eu/1.2/es/) Sota teniu link a conversa amb ChatGPT o1-preview al respecte.

El Llicenciador seria "Institut Montsià".

Queda pendent aclarir les qüestions sobre acords de cessió de drets i reconeixement d'autoria.

Notes:

- [Conversa amb ChatGPT o1-preview sobre l'EUPL i qüestions relacionades](https://chatgpt.com/share/674da13e-5214-8010-bb4a-10a3f3645a55)
- [Comprovació amb Perplexity de la compatibilitat d'EUPL amb MIT i BSD-3-Clause](https://www.perplexity.ai/search/es-compatible-la-licencia-eupl-PFSI3nlTQXeRIj58hgJMPw) Nota: Perplexity dóna per defecte links a les fonts en les que s'ha basat.
- [Resposta de ChatGPT o1-preview a la pregunta "When creating an EUPL 1.2 license, where must I write the name of the Licensor?"](https://chatgpt.com/share/674da38a-9130-8010-a5e2-c07044d57640)
